config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_divise_params, if: :devise_controller?


  def configure_divise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  def saludo 
    @myName = "Cris"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # Esto se ejecutaro solo en el momento de que se usen las acciones descritas
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  # new : Mostrue el formulario para crear una imagen
  def new
    @image = Image.new
  end

  # create: recibe toda la informacion del formulario
  def create
    # Manipula los parametros que se reciben
    #render plain: params[:image].inspect
    
    @image = Image.new image_params
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @image.update image_params
    redirect_to images_path
  end

  def show
  end

  def destroy
    @image.destroy

    redirect_to images_path
  end

  def set_image
    @image = Image.find params[:id]
  end

  private

  def image_params
    params.require(:image).permit(:description, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>  
  <h1>Bienvenido <%= current_user.name %></h1>
<%else%>
  <h1>RailsGram</h1>
<%end%>

app/views/images/_form.html.erb
<div class="form-group">
  <%= form_for @image, builder: CustomFormBuilder do |f| %>  

    <%= f.form_error %>

    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= f.field_error :description %>
    <br/>
    <%= f.label :picture %>
    <%= f.file_field :picture%>
    <br/>
    <%= f.submit 'Enviar', class:'btn btn-primary'%>

  <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-sm">
  <figure class="figure">    
    <%= image_tag image.picture.medium.url, class:"figure-img img-fluid rounded"%>
    <figcaption class="figure-caption text-right">
      <%= image.description %>
      <br/>
      <%= link_to t('.edit_link'), edit_image_path(image) %> 
      <%= link_to t('.destroy_link'), image, method: :delete, data: {confirm: 'sure?'}%>
    </figcaption>
  </figure>
</div>

app/views/images/edit.html.erb
<div class="container">
  <p>Editar Imagen</p>
  <%= render 'form'%>
</div>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <%= render @images %>
  </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <h2>Nueva Imagen</h2>
  <%= render 'form' %>
</div>

app/views/images/show.html.erb
<%= image_tag image.picture.medium.url, class:"figure-img img-fluid rounded"%>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav justify-content-end">
      <% if user_signed_in? %>
        <li class='nav-item'>
          <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class='nav-item'>
          <%= link_to 'Entrar', new_user_session_path%>
        </li>
        <li class='nav-item'>
          <%= link_to 'Registrarme', new_user_registration_path%>
        </li>
      <%end%>
    </ul>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>